### Joining NumPy arrays.
- Joining means putting contents of two or more arrays in a single array.
- In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

### Axis.
- axis = 0, along column (default)
- axis = 1, along rows 

### 1. concatenate( )
- concatenate is used to join to or more arrays in one single array, along a specified axis

In [2]:
import numpy as np 

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

ar_con = np.concatenate((arr1, arr2)) # default column wise


print(ar_con)

[1 2 3 4 5 6 7 8]


In [15]:
# concatenate 2D array
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [6,7]])

ar_con = np.concatenate((arr1, arr2), axis = 0) # column wise

print(ar_con)

[[1 2]
 [3 4]
 [5 6]
 [6 7]]


### 2. stack( )
- We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
- We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [6]:
ar = np.array([1,2,3,4])
ar1 = np.array([9,8,7,6])

ar_stk = np.stack((ar,ar1), axis = 1)

print(ar_stk)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


### 3. dstack
- dstack() to stack along height, which is the same as depth.


In [16]:
ar_1 = np.array([1,2,3,4])
ar_2 = np.array([5,6,7,8])

ar_dstk = np.dstack((ar_1,ar_2))

print(ar_dstk)

print()

ar_1 = np.array([[1,2],
                 [3,4]])
ar_2 = np.array([[5,6],
                 [7,8]])

ar_dstk = np.dstack((ar_1,ar_2))

print(ar_dstk)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


### 4. vstack
- vstack() is used to stack (join) arrays vertically, meaning one array is placed below another (row-wise).

In [ ]:
ar_3 = np.array([[1,2],
                 [3,4]])

ar_4 = np.array([[5,6],
                 [7,8]])

ar_vstk = np.vstack((ar_3, ar_4))

print(ar_vstk)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 5. hstack
- hstack() is used to stack (join) arrays horizontally, meaning arrays are placed side-by-side (column-wise).


In [ ]:
ar_5 = np.array([[1,2],
                 [3,4]])

ar_6 = np.array([[5,6],
                 [7,8]])


ar_hstk = np.hstack((ar_5, ar_6))

print(ar_hstk)

[[1 2 5 6]
 [3 4 7 8]]


### 6. split
- array_split() function is used to divide array into smaller sub-arrays.
- syntax:- np.array_split(var, indices)

In [4]:
ar = np.array([1,2,3,4,5,6])

ar_spl = np.array_split(ar, 3)

print(ar_spl)

[array([1, 2]), array([3, 4]), array([5, 6])]
