# Arithmetic Operator
### 1. Addition

In [2]:
import numpy as np

var = np.array([1,2,3,4])
var_add = var + 3

print(var_add)

[4 5 6 7]


## add( )

In [5]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var_add1 = np.add(var1, var2)
print(var_add1)

[2 4 6 8]


### 2. Subtraction

In [6]:
var = np.array([1,2,3,4])
var_sub = var - 3

print(var_sub)

[-2 -1  0  1]


## subtract( )

In [7]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var_sub1 = np.subtract(var1, var2)
print(var_sub1)

[0 0 0 0]


### 3. Multiplication

In [8]:
var = np.array([1,2,3,4])
var_mul = var * 3

print(var_mul)

[ 3  6  9 12]


## multiply( )

In [9]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var_multi1 = np.multiply(var1, var2)
print(var_multi1)

[ 1  4  9 16]


### 4. Divide

In [12]:
var = np.array([1,2,3,4])
var_divide = var / 3

print(var_divide)

[0.33333333 0.66666667 1.         1.33333333]


## divide( )

In [10]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var_divide1 = np.divide(var1, var2)
print(var_divide1)

[1. 1. 1. 1.]


### 5. Modulus

In [ ]:
var = np.array([1,2,3,4])
var_mod = var % 3

print(var_mod)

## mod( )


In [14]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var_mod1 = np.mod(var1, var2)
print(var_mod1)

[0 0 0 0]
