## Searching and sorting
- Searching is the process of find a specific element in a collection of data.
- Sorting means to sort the array in ascending or descending order.

### This notebook covers.
- where()
- searchsorted()
- sort()
- nonzero()
- argsort()

### 1. np.where()
- Returns the indices of elements that satisfy a condition.


In [1]:
import numpy as np

arr = np.array([5,6,3,4,7,2,8,1])

print(np.where(arr == 4))

(array([3]),)


### 2. np.searchsorted()
- Find the index where a value should be inserted to keep a sorted array in order.

In [3]:
arr1 = np.array([1,2,3,5,6,7,8])
print(np.searchsorted(arr1, 4))

3


### 3. np.sort()
- It sorts the array in ascending or descending order.

In [12]:
arr2 = np.array([4,5,6,8,2,1,9,3])

print(np.sort(arr2)) ## sort in ascending order
print()
print(np.sort(arr2)[::-1]) ## sort in descending order using negative indexing


[1 2 3 4 5 6 8 9]

[9 8 6 5 4 3 2 1]


### 4. np.nonzero()
- Find indices of non-zero elements.

In [13]:
arr3 = np.array([3,5,0,7,2,0,4,1,0])

print(np.nonzero(arr3))

(array([0, 1, 3, 4, 6, 7]),)


### 5. np.argsort()
- Return indices that would sorts an array.

In [14]:
arr4 = np.array([3,5,0,7,2,0,4,1,0])

print(np.argsort(arr4))

[2 5 8 7 4 0 6 1 3]
