# Numpy Dimensions of arrays.


### There are 4 types of dimensions in arrays.
- 1-D Arrays.
- 2-D Arrays.
- 3-D Arrays.
- N-D Arrays.

### 1-D Arrays:- 
- A one-dimensional array is a linear collection of elements stored in a single row, accessed using one index.

In [ ]:
import numpy as np

ar1 = [1,2,3,4]
print(np.array(ar1))

[1 2 3 4]


### 2-D Arrays:-
- A two-dimensional array is a structured collection of elements arranged in rows and columns, accessed using two indices (row and column).

In [3]:
ar2 = [[1,2,3,4],[1,2,3,4]]
print(np.array(ar2))

[[1 2 3 4]
 [1 2 3 4]]


### 3-D Arrays:-
- A three-dimensional array is a collection of two-dimensional arrays stacked together, accessed using three indices.

In [4]:
ar3 = [[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]
print(np.array(ar3))

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


### N-D Arrays:-
- An n-dimensional array is a NumPy array that can have any number of dimensions, where n represents the number of axes.
- ndmin is a parameter in np.array() used to set the minimum number of dimensions of an array.

In [7]:
arn = [1,2,3,4]
print(np.array(arn,ndmin = 10))

[[[[[[[[[[1 2 3 4]]]]]]]]]]


### To check the dimensions of array.
- we can use ndim function.
- In NumPy, ndim stands for number of dimensions of an array.

In [8]:
arn1 = np.array([1,2,3,4], ndmin = 10)
print(arn1)
print(f"The dimensions of an array is {arn1.ndim}")

[[[[[[[[[[1 2 3 4]]]]]]]]]]
The dimensions of an array is 10
