# Special types of Array (filled with specific value)

### 1. Zeros
- It creates an array filled with only zeros.

In [7]:
import numpy as np

ar_zero = np.zeros(3)
ar_zero1 = np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 2. Ones
- It creates an array filled with Ones.

In [8]:
ar_one = np.ones((2,3))
print(ar_one)

[[1. 1. 1.]
 [1. 1. 1.]]


# 3. Empty
- It creates an array without initializing values (contains random memory data)

In [9]:
ar_emp = np.empty((3,4))
print(ar_emp)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 4. Identity array (np.eye())
### An identity matrix is a square matrix in which:
- All the elements in the main diagonal are 1.
- All the other elements are 0.

In [10]:
ar_iden = np.eye(3,3)
print(ar_iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 5. Range 
- It creates evenly spaced values in a range.
- Syntax:- np.arange(start,stop,step)

In [11]:
ar_ran = np.arange(1,10,2)
print(ar_ran)

[1 3 5 7 9]


# 6. Linspace
- It creates evenly spaced numbers between two values.
- Syntax:- np.linspace(start, stop, total_numbers)

In [12]:
ar_lin = np.linspace(0,20,5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
