# Generate Random Numbers.
- Numpy offers the random module to work with random numbers.
- Random module helps in to create the arrays filled with random numbers using numpy.random module.

### 1. rand()
- It is used to generate a random value between 0 to 1.
- Syntax:- np.random.rand(size of array)

In [5]:
import numpy as np

var = np.random.rand(4)
var1 = np.random.rand(3,3)

print(var)
print()
print(var1)

[0.85537234 0.17249375 0.33828967 0.48769028]

[[0.86275376 0.75106741 0.02908941]
 [0.64050946 0.72970565 0.29322531]
 [0.31536788 0.46025907 0.82694137]]


# 2. randn()
- It is used to generate a random value closer to 0.
- This may returns positive or negative numbers as well.
- Syntax:- np.random.randn(size of array)

In [6]:
var2 = np.random.randn(3,4)
print(var2)

[[ 0.98865556  1.30019692  1.2802324  -1.52708135]
 [-3.05379241  0.64611916  0.37072886  0.85202541]
 [ 1.30094498  0.97132246  0.3973344  -1.55158428]]


# 3. randint()
- It is used to generate a random number between a given range.
- Syntax:- np.random.randint(start, end, total_numbers)

In [7]:
var3 = np.random.randint(5, 50, 10)

print(var3)

[13 43 16 18 44 20 29 34 30 29]
