### Indexing.
- Array indexing is the same as accessing an array element.
- We can access an array element by referring to it's index number.
- Note:- Index number starts from zero and goes till n-1.

### Accessing 1-D array

In [9]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print()
print("Value at index 1 is:",arr[1])

[1 2 3 4 5]

Value at index 1 is: 2


### Accessing 2-D array

In [10]:
arr_1 = np.array([[1,2,3,4], [5,6,7,8]])

print(arr_1)
print()
print("2nd element in second row: ",arr_1[1,1])

[[1 2 3 4]
 [5 6 7 8]]

2nd element in second row:  6


### Accesing 3-D array

In [11]:
arr_2 = np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [13,14,15,16]]])

print(arr_2)
print()
print(arr_2[0,1,3])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

8


### Negative Indexing

In [12]:
arr_3 = np.array([[1,2,3,4],[5,6,7,8]])

print("Last element from 2nd dim:",arr_3[1,-1])

Last element from 2nd dim: 8
