### Slicing.
- Slicing in python means taking elements from one given index to another given index.
- We pass slice instead of index like this:- [start:end] or [start:end:step]

### Slicing from index 1 to 5.
- It goes till n-1.

In [1]:
import numpy as np

ar = np.array([1,2,3,4,5,6,7,8,9,10])

print(ar[1:5])

[2 3 4 5]


### Slicing from index 4 to end.

In [2]:
ar_1 = np.array([1,2,3,4,5,6,7,8,9,10])

print(ar[4:])

[ 5  6  7  8  9 10]


### Negative Slicing.


In [3]:
ar_2 = np.array([1,2,3,4,5,6,7,8,9,10])

print(ar[-5:-2])

[6 7 8]


### Step.

In [4]:
ar_3 = np.array([1,2,3,4,5,6,7,8,9,10])

print(ar[1:9:2])

[2 4 6 8]
