## Numpy Array Shape
### Shape of an Array
- The Shape of an array is the number of element in each dimension.
- Numpy Arrays have an attribute called shape that returns a tuple representing the size of the array in each dimension.

### Shape

In [2]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])
print("The Shape of the 2-D array is:", arr.shape)

The Shape of the 2-D array is: (2, 4)


In [3]:
arr_1 = np.array([1,2,3,4], ndmin = 5)
print("The Shape of the array is:", arr_1.shape)

The Shape of the array is: (1, 1, 1, 1, 4)


### Reshaping arrays
- Reshaping means changing the shape of an array.
- The shape of an array is the number of elements in each dimension.
- By reshaping we can add or remove dimensions or change number of elements in each dimension.

- Example:- Reshape from 1-D to 2-D

In [4]:
arr_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr_2.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


- Reshape from 1-D to 3-D

In [5]:
arr_3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr_3.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Flattening the arrays
- Flattening array means converting a multidimensional array into a 1D array.

- We can use reshape(-1) to do this.

In [6]:
arr_4 = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr_4.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


### Transpose of array
- Transpose in NumPy is an operation that interchanges the rows and columns of an array, producing a new view of the same data with reversed axes.

- Example:

In [7]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

transposed = arr.T
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


### Resize of array
- Resize in NumPy is a method used to change the shape and size of an array by modifying the original array itself.

In [11]:
arr = np.array([1, 2, 3, 4])
arr.resize((3, 2))
print(arr)

[[1 2]
 [3 4]
 [0 0]]
